version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - './app:/app'
    - '/app/node_modules'
    ports:
    - '3000:3000'
    environment:
    - NODE_ENV=development
    #command: npm run build